# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Memestagram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memestagram
	pod 'Firebase/Auth'
	pod 'Firebase/Analytics'
	pod 'Firebase/Messaging'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
end

